name: Update rolling Microsoft Edge release (MSI attached)

on:
  schedule:
    - cron: "17 */4 * * *"   # every 4 hours
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Fetch Edge Updates API
        run: |
          set -e
          curl -fsSL "https://edgeupdates.microsoft.com/api/products?view=enterprise" > edge.json

      - name: Parse latest Stable Windows x64 MSI
        id: parse
        run: |
          set -e
          # Get the latest Stable Windows x64 version
          VERSION=$(jq -r '
            .[] | select(.Product=="Stable")
            | .Releases[]? 
            | select(.Platform=="Windows" and .Architecture=="x64")
            | .ProductVersion
          ' edge.json | sort -V | tail -n1)

          # Get the MSI URL for that version
          MSI_URL=$(jq -r --arg VER "$VERSION" '
            .[] | select(.Product=="Stable")
            | .Releases[]? 
            | select(.ProductVersion==$VER and .Platform=="Windows" and .Architecture=="x64")
            | .Artifacts[]? 
            | select(.ArtifactName=="msi")
            | .Location
          ' edge.json | head -n1)

          echo "Parsed version: $VERSION"
          echo "Parsed MSI URL: $MSI_URL"

          if [ -z "$MSI_URL" ]; then
            echo "No MSI URL found for Stable Windows x64 version $VERSION"
            exit 1
          fi

          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "msi_url=$MSI_URL" >> "$GITHUB_OUTPUT"

      - name: Download MSI from Microsoft
        run: |
          set -e
          mkdir -p out
          echo "Downloading: ${{ steps.parse.outputs.msi_url }}"
          curl -fL --retry 5 --retry-delay 2 \
            -o out/MicrosoftEdgeEnterpriseX64.msi \
            "${{ steps.parse.outputs.msi_url }}"
          sha256sum out/MicrosoftEdgeEnterpriseX64.msi | tee out/SHA256.txt

      - name: Update rolling release with MSI
        uses: ncipollo/release-action@v1
        with:
          tag: Edge
          name: Microsoft Edge
          body: |
            Channel: Stable
            Platform: Windows x64
            Version: ${{ steps.parse.outputs.version }}

            MSI downloaded from Microsoft CDN and attached automatically.
          allowUpdates: true
          replacesArtifacts: true
          artifacts: |
            out/MicrosoftEdgeEnterpriseX64.msi
            out/SHA256.txt
          draft: false
          prerelease: false
