name: Update rolling Microsoft Edge release (MSI attached)

on:
  schedule:
    - cron: "17 */4 * * *"   # every 4 hours
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Fetch Edge Updates API
        run: |
          curl -fsSL "https://edgeupdates.microsoft.com/api/products?view=enterprise" > edge.json

      - name: Parse latest Stable Windows x64 MSI
        id: parse
        run: |
          VERSION=$(jq -r '
            .[] | select(.Product=="Stable")
            | .Releases[]? | .ProductVersion
          ' edge.json | sort -V | tail -n1)

          MSI_URL=$(jq -r --arg VER "$VERSION" '
            .[] | select(.Product=="Stable")
            | .Releases[]? | select(.ProductVersion==$VER)
            | ( .Artifacts[]?, .Platforms[]?.Artifacts[]? )
            | select((.Platform // "" | ascii_downcase)=="windows"
                     and (.Architecture // "" | ascii_downcase)=="x64"
                     and (.InstallerType // "" | ascii_downcase)=="msi")
            | .Location
          ' edge.json | head -n1)

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "msi_url=$MSI_URL" >> $GITHUB_OUTPUT

      - name: Download MSI from Microsoft
        run: |
          mkdir -p out
          curl -fL --retry 5 --retry-delay 2 \
            -o out/MicrosoftEdgeEnterpriseX64.msi \
            "${{ steps.parse.outputs.msi_url }}"
          sha256sum out/MicrosoftEdgeEnterpriseX64.msi | tee out/SHA256.txt

      - name: Update rolling release with MSI
        uses: ncipollo/release-action@v1
        with:
          tag: Edge
          name: Microsoft Edge
          body: |
            Channel: Stable
            Platform: Windows x64
            Version: ${{ steps.parse.outputs.version }}

            MSI downloaded from Microsoft and attached automatically.
          allowUpdates: true
          replacesArtifacts: true
          artifacts: |
            out/MicrosoftEdgeEnterpriseX64.msi
            out/SHA256.txt
          draft: false
          prerelease: false
